services:
  - type: web
    name: chess-personal-analytics
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    healthCheckPath: /
